[build]
  publish = "website"
  command = "echo no build"

[build.environment]
  PYTHON_VERSION = "3.11"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:8000/api/:splat"
  status = 200
